name: Omikuji
author: ironingot.net
website: ironingot.net 
main: net.ironingot.omikuji.Omikuji
version: 1.3
commands:
  omikuji:
    usage: |
      /<command>
      Example: /<command> [draw] - Draw Omikuji!
      Example: /<command> reload - Reload config.yml 
    description: "Let's Omikuji!"
permissions:
  omikuji.command.draw:
    description: "Draw omikuji"
    default: true
  omikuji.command.draw.others:
    description: "Draw other player's omikuji"
    default: op
  omikuji.command.reload:
    description: "Reload omikuji config"
    default: op
